added current milk price to user page
ucsb-cs156-s23/proj-happycows-s23-6pm-3 pull request #19
Opened 2023-05-25 21:20 UTC by MaximillianStewart

added code to display milk price on the cows column

2023-05-28 23:08 UTC, MrJacobEisner submitted a review, later dismissed

2023-05-29 01:19 UTC, Anshuman-UCSB approved these changes, later dismissed
lgtm

2023-05-29 23:02 UTC, pconrad requested changes
Please do not remove .env.SAMPLE

<img width="763" alt="image" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/assets/1119017/48099aaa-b686-4c56-90dc-76a2a697161b">

2023-05-29 23:08 UTC, pconrad commented
@MaximillianStewart Please consider adding screenshots and storybook links to the description, similar to #22

2023-05-31 20:18 UTC, pconrad requested changes
The storybook needs to be updated to support this change.

Here's how... in the file:

`frontend/src/stories/components/Commons/ManageCows.stories.mdx`

You'll see this line:

```jsx
    <ManageCows userCommons = {userCommonsFixtures.oneUserCommons[0]} onBuy={(userCommons) => { console.log("onBuy called:",userCommons); }} onSell={ (userCommons) => { console.log("onSell called:",userCommons); }} />
```

Which we can first reformat to make it easier to read:
```jsx
 <ManageCows 
    userCommons = {userCommonsFixtures.oneUserCommons[0]} 
    onBuy={(userCommons) => { console.log("onBuy called:",userCommons); }} 
    onSell={ (userCommons) => { console.log("onSell called:",userCommons); }} 
 />
```

We need to add another parameter `commons = {commonsFixtures.oneCommons[0]} ` to pass in a fixture for the commons, maybe something like this:

```
```jsx
 <ManageCows 
    commons = {commonsFixtures.oneCommons[0]} 
    userCommons = {userCommonsFixtures.oneUserCommons[0]} 
    onBuy={(userCommons) => { console.log("onBuy called:",userCommons); }} 
    onSell={ (userCommons) => { console.log("onSell called:",userCommons); }} 
 />
```

Then the story should start working properly.

2023-05-31 20:18 UTC, pconrad commented on frontend/src/main/components/Commons/ManageCows.js
> +            <Card.Title>Current Milk Price: ${commons?.milkPrice} </Card.Title>
It appears the the storybook component for ManageCows needs to be updated to support this.  Right now it looks like this:

<img width="898" alt="image" src="https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/assets/1119017/495db244-941c-415f-a067-64679e77b9c4">

follow [link](https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-3/prs/19/storybook/?path=/story/components-commons-managecows--uncontrolled) to see for yourself

I'll outline the fix in the next comment.

2023-05-31 20:25 UTC, pconrad approved these changes
LGTM... though the storybook entry should be updated in a different PR (for 5 more points)

2023-05-31 20:25 UTC, merged