ms - updated link to this repository
ucsb-cs156-s23/proj-happycows-s23-6pm-3 pull request #54
Opened 2023-06-05 22:48 UTC by MaximillianStewart

Changed link destination in footer to link user to this repository instead of course projects repo

2023-06-06 17:54 UTC, pconrad requested changes
So this is setting the url to the one for your specific team.  There is a change needed, since the default is `proj-courses`, which is definitely wrong.

But you shoudn't set the default to the specific url for your team.  Instead, set it to 

```
https://github.com/ucsb-cs156/proj-happycows
```

The right way to do this so that your your team deployments point to your team's repo is to just override the local .env file on localhost, and/or create a config variable on your dokku deployments:

```
dokku config:set proj-happycows SOURCE_REPO=https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3
dokku config:set proj-happycows-qa SOURCE_REPO=https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3
```

The whole reason the code is structured like this is so that we do NOT need to change this for every team.  This can't be merged into the main branch, becuase then the main branch can't be merged into the long-term main branch, where

2023-06-06 17:54 UTC, pconrad commented on frontend/src/tests/components/Nav/Footer.test.js
> +        expect(href).toHaveAttribute("href", "https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3");
```suggestion
        expect(href).toHaveAttribute("href", "https://github.com/ucsb-cs156/proj-happycows");
```

2023-06-06 17:54 UTC, pconrad commented on src/main/resources/application-development.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3}}
```suggestion
app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156/proj-happycows}}
```

2023-06-06 17:54 UTC, pconrad commented on src/main/resources/application.properties
> +app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3}}
```suggestion
app.sourceRepo=${SOURCE_REPO:${$env.SOURCE_REPO:https://github.com/ucsb-cs156/proj-happycows}}
```

2023-06-06 17:54 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
> +        .sourceRepo("https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3")
```suggestion
        .sourceRepo("https://github.com/ucsb-cs156/proj-happycows")
```

2023-06-08 02:35 UTC, MrJacobEisner commented
Feel free to reopen, Im closing this to help cleanup our pr queue

2023-06-08 02:35 UTC, closed without merging