FEATURE: Added End Date, cows are not milked and cow health does not degrade after end date
ucsb-cs156-s23/proj-happycows-s23-6pm-3 pull request #59
Opened 2023-06-06 05:08 UTC by epuzio

2023-06-06 20:28 UTC, MrJacobEisner commented on frontend/src/main/components/Commons/CommonsForm.js
Do you think the default value should be today?

2023-06-06 20:29 UTC, MrJacobEisner submitted a review, later dismissed

2023-06-06 20:50 UTC, epuzio commented on frontend/src/main/components/Commons/CommonsForm.js
For lastDate? Good point, I can fix that.

2023-06-06 21:46 UTC, MaximillianStewart approved these changes, later dismissed
LGTM

2023-06-06 21:47 UTC, awaang approved these changes, later dismissed

2023-06-08 01:24 UTC, pconrad commented on package.json
> +}
Why is this here?   My guess is that someone did an npm install in the wrong directory and created this by accident.   

We only want a package.json inside the frontend directory.

Can we remove this from the PR?

2023-06-08 01:26 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJob.java
> +                    if(userCommons.gameInProgress()){
Why are we checking this at the userCommons level?

The game is in progress, or not, at the Commons level, not at the UserCommons level.

It doesn't make sense to iterate over every player and make the same check for each one. This check should be at the outer loop.

2023-06-08 01:27 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
> +  private LocalDateTime lastDate;
Why?   These fields go on the Commons, not the UserCommons!

2023-06-08 01:27 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
> +  private LocalDateTime lastDate;
You have the fields here.  You do not need them, and should not store them redundantly on the UserCommons.

2023-06-08 01:28 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
> +  public boolean gameInProgress(){
Please move this function to the Commons.  It belongs there, not on the UserCommons.

2023-06-08 01:31 UTC, pconrad requested changes
A few things... mostly having to do with NOT storing redundant data on the UserCommons when we can get it through the commons.

2023-06-08 01:31 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJob.java
> +                ctx.log("Milking cows for Commons: " + name + ", Milk Price: " + formatDollars(milkPrice));
This is where you should check:

```suggestion
                if (!commons.gameInProgress()) {
                    ctx.log("Commons " + name + " is not currently in progress, and cows were not milked.");
                } else { 
                   ctx.log("Milking cows for Commons: " + name + ", Milk Price: " + formatDollars(milkPrice));
                   // etc...  be sure to close this brace...
```

2023-06-08 01:31 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
> +                if(userCommons.gameInProgress()){
Please fix this one in a similar way

2023-06-08 01:31 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
> +        double degradationRate, boolean gameInProgress) {
Why do we need this?

We can just avoid calling the function in the first place.  Note that you didn't use the value inside the function.

2023-06-08 03:11 UTC, MrJacobEisner approved these changes
Some whitespace issues, but the code looks good. Aside from that,  assuming Professor Conrad's comment is resolved, LGTM.

2023-06-08 04:21 UTC, awaang approved these changes
LGTM

2023-06-08 05:30 UTC, pconrad approved these changes
LGTM!  Will test on staff-qa before merging

2023-06-08 21:48 UTC, merged